"""requests table

Revision ID: 4c9f07e6aff3
Revises: b555eeaefad2
Create Date: 2020-12-01 13:35:56.843250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9f07e6aff3'
down_revision = 'b555eeaefad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_date'), 'request', ['date'], unique=True)
    op.create_index(op.f('ix_request_timestamp'), 'request', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_timestamp'), table_name='request')
    op.drop_index(op.f('ix_request_date'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
